**1**

In [2]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
df = pd.DataFrame(columns=['Название','Адрес','Макс. оценка','Средняя оценка'])
sanatoriy = ['metallurg','zapolyarie','burgas','odissey','rus-avangard','znanie-adler','fregat','sputnik']
c=0
for i in sanatoriy:
    c+=1
    url = 'https://русские-курорты.рф/sochi/sanatory/'+i
    res = requests.get(url)
    soup = BeautifulSoup(res.text,'html.parser')
    rating = soup.find_all('a', class_='btn pull-right btn-primary')
    rating = np.array([float(i.text[-3:]) for i in rating])
    location = soup.find_all('a',class_='under', target='_blank')[0].text.replace('/xa0','').replace('Адрес:','')
    name = soup.find_all('span', itemprop="name")[3].text
    df.loc[c] = [name, location, rating.max(), rating.mean()]

In [3]:
df

,Название,Адрес,Макс. оценка,Средняя оценка
1,Санаторий Металлург,"г. Сочи, ул. Курортный проспект, 92",9.3,8.512500
2,Санаторий Заполярье,"г. Сочи, ул. Пирогова, 10",9.8,7.375000
3,Пансионат Бургас,"г. Сочи, п. Кудепста, ул. Ленина, 233",9.8,8.380000
4,Санаторно-курортный комплекс Одиссея Wellness ...,"г. Сочи, п. Лазаревское, ул. Сочинское шоссе...",8.8,8.733333
5,Санаторий Авангард,"г. Сочи, ул. Курортный Проспект, 83",9.8,7.875000
6,Санаторий Знание,"Сочи, г. Адлер, ул. Просвещения,139",9.3,6.922222
7,Пансионат Фрегат,"г. Сочи, Адлерский район, ул. Ленина, 219",9.4,6.964706
8,Отель Alean Family Resort & Spa Sputnik 4*,"г. Сочи, Новороссийское шоссе, 17/1",9.6,9.450000

**2**

In [ ]:
df = pd.DataFrame(columns = ['Name','Genre','Rating Critics','Rating Viewers'])
url = 'https://metarankings.ru/best-movies/'
res = requests.get(url)
soup = BeautifulSoup(res.content,'html.parser')
genre = [i.text.replace('Жанр:','') for i in soup.find_all('p')][2:]
rating1 = [i.text[1:4].replace('\nЗ','.0').replace('\nР','.0') for i in soup.find_all('div', class_="graph")][::2]
rating2 = [i.text[1:4].replace('\nЗ','.0').replace('\nР','.0') for i in soup.find_all('div', class_="graph")][1::2]
title = soup.find_all('a', class_="name")
i = 1
for t, g, r1, r2 in zip(title, genre, rating1, rating2):
    df.loc[i] = [t.get_text(), g, r1, r2]
    i += 1

In [ ]:
df

,Name,Genre,Rating Critics,Rating Viewers
1,Терминатор 2: Судный день в 3D,"Боевики, Фантастика",9.5,8.2
2,Гравитация,Фантастика,9.2,7.5
3,Безумный Макс: Дорога ярости,"Боевики, Фантастика",9.1,7.6
4,Грань будущего,"Боевики, Фантастика",9.0,7.6
5,Выживший,"Драмы, Исторические, Триллеры",8.8,7.8
6,Интерстеллар,Фантастика,8.5,8.0
7,Kingsman: Секретная служба,"Боевики, Комедии",8.8,7.6
8,Приключения Паддингтона 2,Семейные,8.8,7.6
9,Джокер,"Триллеры, Фантастика",8.7,7.7
10,Ирландец,"Драмы, Исторические",9.1,7.4
11,Первый мститель: Противостояние,"Боевики, Фантастика",8.7,7.6
12,Одержимость,Мелодрамы,9.0,7.3
13,Стражи галактики: Праздничный спецвыпуск,"Комедии, Фантастика",9.3,7.1
14,Агенты А.Н.К.Л.,"Боевики, Комедии",8.2,8.0
15,Круэлла,Комедии,7.7,8.5
16,Логан,"Боевики, Фантастика",8.4,7.8
17,Суспирия,Триллеры,8.6,7.5
18,Стартрек: Бесконечность,"Боевики, Фантастика",8.3,7.8
19,Оно,Ужасы,8.2,7.9
20,Стражи Галактики,"Боевики, Фантастика",7.9,8.1
21,Дэдпул,"Боевики, Фантастика",8.4,7.6
22,Прочь,Ужасы,8.3,7.7
23,Исчезнувшая,"Мелодрамы, Триллеры",9.1,6.9
24,На Западном фронте без перемен,"Боевики, Военные, Драмы, Исторические",8.7,7.4
25,Солнце моё,Драмы,8.7,6.8
26,Омерзительная восьмерка,"Боевики, Триллеры",8.2,7.7
27,Хардкор,"Боевики, Фантастика",8.3,7.6
28,Джентльмены,Боевики,8.3,7.6
29,"Дом, который построил Джек",Триллеры,8.5,7.4
30,Бёрдмэн,"Комедии, Мелодрамы",9.1,6.8
31,Дом странных детей Мисс Перегрин,Фэнтези,7.7,8.1
32,Мстители: Война бесконечности,"Боевики, Фантастика",7.8,8.0
33,Люди Икс: Дни минувшего будущего,Фантастика,7.9,7.9
34,Мстители 2: Эра Альтрона,"Боевики, Фантастика, Фэнтези",8.2,7.6
35,Доктор Стрэндж,Фэнтези,8.0,7.8
36,Аритмия,Мелодрамы,8.7,7.2
37,Зеленая книга,Комедии,8.3,7.6
38,Приключения Реми,"Комедии, Мелодрамы",7.8,8.1
39,Лакричная пицца,"Комедии, Мелодрамы",8.4,7.5
40,Не дыши,Триллеры,8.0,7.7
41,Фантастические твари и где они обитают,"Семейные, Фэнтези",8.3,7.4
42,Айта,"Драмы, Триллеры",7.5,7.7
43,Ла-Ла Ленд,"Комедии, Мелодрамы",8.8,7.0
44,Прибытие,"Триллеры, Фантастика",8.6,7.2
45,Однажды… в Голливуде,Комедии,8.8,7.0
46,Паразиты,"Драмы, Комедии, Триллеры",8.6,7.2
47,Человек из стали,"Боевики, Фантастика",8.0,7.6
48,Прогулка,"Мелодрамы, Триллеры",7.9,7.7
49,Первому игроку приготовиться,"Боевики, Семейные, Фантастика, Фэнтези",7.6,8.0
50,Дюнкерк,"Военные, Драмы",7.9,7.7

**3**

In [5]:
df = pd.DataFrame(columns = ['Name','Year','Rating'])
url = 'https://www.imdb.com/chart/top'
res = requests.get(url)
soup = BeautifulSoup(res.content,'html.parser')
year = soup.find_all('span', class_='secondaryInfo')
rating = soup.find_all('strong')
titles2 = [i.text for i in soup.find_all('td', class_="titleColumn")]
title = [i[16:-8].strip() for i in titles2]
i = 1
for t, y, r in zip(title, year, rating):
    df.loc[i] = [t, y.get_text(), r.get_text()]
    i += 1

In [6]:
df

                         Name    Year Rating
1    The Shawshank Redemption  (1994)    9.2
2               The Godfather  (1972)    9.2
3             The Dark Knight  (2008)    9.0
4       The Godfather Part II  (1974)    9.0
5                12 Angry Men  (1957)    9.0
..                        ...     ...    ...
246            The Iron Giant  (1999)    8.0
247                  The Help  (2011)    8.0
248               Dersu Uzala  (1975)    8.0
249                   Aladdin  (1992)    8.0
250        Dances with Wolves  (1990)    8.0

[250 rows x 3 columns]

**3.1**

In [ ]:
df = pd.DataFrame(columns = ['Name','Author','Rating'])
url = 'https://www.livelib.ru/genre/Триллеры/best'
res = requests.get(url)
soup = BeautifulSoup(res.content,'html.parser')
titles = soup.find_all('a', class_='brow-book-name with-cycle')
authors = soup.find_all('a', class_='brow-book-author')
rating = soup.find_all('span', class_='rating-value stars-color-orange')
i = 1
for t, a, r in zip(titles, authors, rating):
    df.loc[i] = [t.get_text(), a.get_text(), r.get_text()]
    i += 1

In [ ]:
df

                             Name            Author Rating
1                        Парфюмер    Патрик Зюскинд   4.24
2                    Коллекционер        Джон Фаулз   4.20
3                    Код да Винчи         Дэн Браун   4.27
4                         Ребекка    Дафна дю Морье   4.33
5                 Ангелы и демоны         Дэн Браун   4.33
6   Девушка с татуировкой дракона      Стиг Ларссон   4.42
7                Девушка в поезде       Пола Хокинс   3.74
8               Побег из Шоушенка       Стивен Кинг   4.60
9                  Тайная история       Донна Тартт   4.31
10             Безмолвный пациент  Алекс Михаэлидес   4.09
11                    Милые кости       Элис Сиболд   3.91
12                  Внутри убийцы         Майк Омер   4.38
13                        Инферно         Дэн Браун   4.28
14                    Исчезнувшая     Гиллиан Флинн   4.17
15   Правда о деле Гарри Квеберта      Жоэль Диккер   4.37
16                       Нетопырь           Ю Несбё   3.70
17          The One. Единственный        Джон Маррс   4.17
18  Семь смертей Эвелины Хардкасл     Стюарт Тёртон   4.05
19              Утраченный символ         Дэн Браун   4.18
20                Долгая прогулка     Ричард Бахман   4.28
21                       Имя розы       Умберто Эко   4.34
22                  Охота на овец   Харуки Мураками   4.15
23              Цифровая крепость         Дэн Браун   3.98
24                 Молчание ягнят      Томас Харрис   4.47
25                Мистер Мерседес       Стивен Кинг   4.31